const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Qazi❤",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "X-Qazi",
  ownername:process.env.OWNER_NAME|| "Qazi",

  sessionName:process.env.SESSION_ID || "SUHAIL_08_05_09_09_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTI4LFxuICAgICAgICAxMTMsXG4gICAgICAgIDEzNCxcbiAgICAgICAgOTAsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTI3LFxuICAgICAgICA5MyxcbiAgICAgICAgMTU3LFxuICAgICAgICAxNTIsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTIyLFxuICAgICAgICAxNixcbiAgICAgICAgNjcsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTk2LFxuICAgICAgICAxNDgsXG4gICAgICAgIDIxMSxcbiAgICAgICAgNDcsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTIwLFxuICAgICAgICAxNDMsXG4gICAgICAgIDIwLFxuICAgICAgICAxODgsXG4gICAgICAgIDU4LFxuICAgICAgICAxNzIsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTYwLFxuICAgICAgICAzMixcbiAgICAgICAgMTU1LFxuICAgICAgICAyNDQsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTEzXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDgwLFxuICAgICAgICA5MixcbiAgICAgICAgNDcsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTcsXG4gICAgICAgIDU3LFxuICAgICAgICAxMzMsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjQzLFxuICAgICAgICAxODksXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjQxLFxuICAgICAgICAxNzAsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMTk0LFxuICAgICAgICA5NCxcbiAgICAgICAgMTIsXG4gICAgICAgIDEzMCxcbiAgICAgICAgOTksXG4gICAgICAgIDE2NixcbiAgICAgICAgOTQsXG4gICAgICAgIDcxLFxuICAgICAgICA3NSxcbiAgICAgICAgMTM0LFxuICAgICAgICA2NyxcbiAgICAgICAgNTksXG4gICAgICAgIDExNyxcbiAgICAgICAgMjAxLFxuICAgICAgICAyOCxcbiAgICAgICAgNDMsXG4gICAgICAgIDE3OCxcbiAgICAgICAgNzBcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDU2LFxuICAgICAgICA4NCxcbiAgICAgICAgOTMsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjM2LFxuICAgICAgICAxOTEsXG4gICAgICAgIDY1LFxuICAgICAgICA2NCxcbiAgICAgICAgMTE1LFxuICAgICAgICAyNDgsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMzAsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTMxLFxuICAgICAgICAzMCxcbiAgICAgICAgMTM1LFxuICAgICAgICAxODgsXG4gICAgICAgIDU3LFxuICAgICAgICA4NixcbiAgICAgICAgMjIxLFxuICAgICAgICAyMjAsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMjUzLFxuICAgICAgICA5OSxcbiAgICAgICAgMjQ5LFxuICAgICAgICAyNTAsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjQ0LFxuICAgICAgICA4NSxcbiAgICAgICAgMTM4LFxuICAgICAgICAxNjEsXG4gICAgICAgIDk1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyLFxuICAgICAgICAyNCxcbiAgICAgICAgMTE1LFxuICAgICAgICA3MCxcbiAgICAgICAgMTg2LFxuICAgICAgICAxMzcsXG4gICAgICAgIDQ2LFxuICAgICAgICAyMDIsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMjExLFxuICAgICAgICA2MyxcbiAgICAgICAgMTE1LFxuICAgICAgICAxMjUsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTcwLFxuICAgICAgICA4MixcbiAgICAgICAgOSxcbiAgICAgICAgMjYsXG4gICAgICAgIDkzLFxuICAgICAgICAxOTUsXG4gICAgICAgIDI2LFxuICAgICAgICA3OSxcbiAgICAgICAgODUsXG4gICAgICAgIDc1LFxuICAgICAgICAxMjksXG4gICAgICAgIDE2LFxuICAgICAgICA3OSxcbiAgICAgICAgMjA1LFxuICAgICAgICAxNjAsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjA5LFxuICAgICAgICA1NVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDAsXG4gICAgICAgIDE3LFxuICAgICAgICAyMzMsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTYzLFxuICAgICAgICAyNTEsXG4gICAgICAgIDMzLFxuICAgICAgICA3NCxcbiAgICAgICAgNSxcbiAgICAgICAgMTY5LFxuICAgICAgICA0MCxcbiAgICAgICAgMjQwLFxuICAgICAgICA4MyxcbiAgICAgICAgMjcsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMjEzLFxuICAgICAgICAxMTEsXG4gICAgICAgIDUwLFxuICAgICAgICAyMzcsXG4gICAgICAgIDkzLFxuICAgICAgICAxMTYsXG4gICAgICAgIDMzLFxuICAgICAgICAxMjksXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTI2LFxuICAgICAgICA4MyxcbiAgICAgICAgMjYsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTc0LFxuICAgICAgICA0NSxcbiAgICAgICAgMjQyLFxuICAgICAgICA3OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0OSxcbiAgICAgICAgMjksXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjEwLFxuICAgICAgICAxNjksXG4gICAgICAgIDE3NixcbiAgICAgICAgMjQyLFxuICAgICAgICA3NyxcbiAgICAgICAgMzksXG4gICAgICAgIDE4NixcbiAgICAgICAgNjIsXG4gICAgICAgIDE1NSxcbiAgICAgICAgNDksXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTY2LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjE0LFxuICAgICAgICAzMCxcbiAgICAgICAgMTMwLFxuICAgICAgICAyNCxcbiAgICAgICAgMTI5LFxuICAgICAgICA2LFxuICAgICAgICAxMSxcbiAgICAgICAgMTA4LFxuICAgICAgICA2MSxcbiAgICAgICAgMTE3LFxuICAgICAgICAxMTIsXG4gICAgICAgIDEwLFxuICAgICAgICAyMTcsXG4gICAgICAgIDksXG4gICAgICAgIDQ4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICA0MSxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAyOCxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgODFcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDEwMCxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgMjUyLFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAxODMsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMzEsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICA5NyxcbiAgICAgICAgICA2OFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDAsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjAwLFxuICAgICAgICAyMDAsXG4gICAgICAgIDE0NSxcbiAgICAgICAgOTgsXG4gICAgICAgIDg1LFxuICAgICAgICAyNDcsXG4gICAgICAgIDIyLFxuICAgICAgICAxMzIsXG4gICAgICAgIDkzLFxuICAgICAgICAxNDUsXG4gICAgICAgIDI0NixcbiAgICAgICAgODYsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTA0LFxuICAgICAgICAyMDIsXG4gICAgICAgIDEzOSxcbiAgICAgICAgNTMsXG4gICAgICAgIDM1LFxuICAgICAgICAyMTAsXG4gICAgICAgIDUzLFxuICAgICAgICAxMzIsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTIyLFxuICAgICAgICAxOTcsXG4gICAgICAgIDI0NCxcbiAgICAgICAgNTgsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMjA2LFxuICAgICAgICA0NCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxNjEsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTQyLFxuICAgICAgICAyMjEsXG4gICAgICAgIDI1LFxuICAgICAgICAxMTcsXG4gICAgICAgIDM1LFxuICAgICAgICA3LFxuICAgICAgICA4NyxcbiAgICAgICAgNTAsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTIxLFxuICAgICAgICA5NixcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMjUsXG4gICAgICAgIDEzNCxcbiAgICAgICAgODMsXG4gICAgICAgIDI0LFxuICAgICAgICAxMyxcbiAgICAgICAgMTk3LFxuICAgICAgICAxMDIsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTY3LFxuICAgICAgICAxMzUsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjUxLFxuICAgICAgICAyMjEsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTQ4LFxuICAgICAgICAzOCxcbiAgICAgICAgMjEwLFxuICAgICAgICAxMjlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDY5LFxuICBcImFkdlNlY3JldEtleVwiOiBcIlRDWkRNWUVheWYvT0ZwQnZqMEpjVVMyK2Y1bTJ6Rm5FOGNmY3lZMENSV2c9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMzE5MTk4MzIxQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI2NUM3MTU5QTEyRTk5OEU4MUYyRkU3MzNFREY1MzNBQVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjU4NjkxNDlcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiOGp0QXpfYkFSYmlxM3NLX0l4amgtUVwiLFxuICBcInBob25lSWRcIjogXCJkZWRkMTY2ZS1jZjUxLTRiMmItYTFjMy03MmRjZmQxNmYwM2NcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNyxcbiAgICAgIDE5MixcbiAgICAgIDYxLFxuICAgICAgMjIsXG4gICAgICAxODksXG4gICAgICAyNDUsXG4gICAgICAxMDIsXG4gICAgICAyMTIsXG4gICAgICAyOSxcbiAgICAgIDE5LFxuICAgICAgMTA4LFxuICAgICAgNTYsXG4gICAgICAyMjUsXG4gICAgICAxNDUsXG4gICAgICAxLFxuICAgICAgNzAsXG4gICAgICAxNzMsXG4gICAgICAyMzgsXG4gICAgICAxMzEsXG4gICAgICAxMDVcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjI4LFxuICAgICAgMTk2LFxuICAgICAgMTIyLFxuICAgICAgMjMyLFxuICAgICAgMTQzLFxuICAgICAgMTEyLFxuICAgICAgMTMsXG4gICAgICAxNjMsXG4gICAgICA1NyxcbiAgICAgIDEyMCxcbiAgICAgIDE4MixcbiAgICAgIDExNSxcbiAgICAgIDE0NSxcbiAgICAgIDIyNSxcbiAgICAgIDE3OSxcbiAgICAgIDE3MSxcbiAgICAgIDI1NCxcbiAgICAgIDEyMCxcbiAgICAgIDcsXG4gICAgICAxODZcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiMjFUVjJXTDVcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzMxOTE5ODMyMToyMUBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIvCdmoLwnZqR8J2aivCdmpHwnZqO8J2ajvCdmptcIixcbiAgICBcImxpZFwiOiBcIjE3Njg2Mjg5NDQ5NzgxMzoyMUBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNObUtuZUlHRU5iWStyWUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIlVVeEIvNVA0enFXUVFMMDB5ZlpBRHFjaE9KNjdYYit6MCtOcER0UWZUMmM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiNTZMUHJmdWQ2OHA1R1ZNYm9takNCOThhNGx6ak52TC9BQWtOSHNHaCtaUkowRkRYdXVoUVN4cmpYbHA0ZDJucmR5MXRiRHRSMWJhUmE2d2hxRytYQ0E9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiWVRoRVhzYTNlZWxlQURnNkp0UzEzWFdxREMxYWtkS3lkWWN4WTc3Rk5rWGhLNzZBdGpYUkRWQng4MWZmb2ZmNGx4cXBYNTRyRE1EazgxclAxa1pRaEE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTIzMzE5MTk4MzIxOjIxQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMzEsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMTAzXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjU4NjkxNDUsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFMczFcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxzMS5qc29uIjogIntcImtleURhdGFcIjpcInV3QXRCdGRlYXEzZ1pkT1pvdVZ3ZFI3a2diekxqaFJoMGh4QThLbU1EQjg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTgxNjYxMDEzNixcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzAsMiwzXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
